HEALTHCARE_IMPLICIT = [
    {"text": "The patient remained NPO for 18 hours. Her blood glucose dropped to 42 mg/dL.", "relations": ["npo_status <causes> hypoglycemia"]},
    {"text": "The ICU was at 98% capacity. Three patients were held in the ED overnight.", "relations": ["icu_overcapacity <causes> ed_boarding"]},
    {"text": "Post-op pain management was inadequate. The patient's respiratory rate climbed to 28 breaths/min.", "relations": ["inadequate_pain_control <causes> tachypnea"]},
    {"text": "Wound dressing changes were missed over the weekend. Culture grew Pseudomonas on Tuesday.", "relations": ["missed_wound_care <causes> wound_infection"]},
    {"text": "The night shift had one nurse for twelve patients. Two patients fell within six hours.", "relations": ["understaffing <causes> patient_falls"]},
    {"text": "The CT scanner was down for maintenance. Diagnosis was delayed four hours.", "relations": ["equipment_downtime <causes> diagnosis_delay"]},
    {"text": "She had been on corticosteroids for six weeks. Her blood pressure was 168/102 mmHg.", "relations": ["corticosteroid_use <causes> hypertension"]},
    {"text": "He received vancomycin without dose adjustment for renal function. Creatinine rose to 3.2 mg/dL.", "relations": ["vancomycin_without_adjustment <causes> acute_kidney_injury"]},
    {"text": "Aspiration occurred during intubation. Bilateral infiltrates appeared on chest X-ray 48 hours later.", "relations": ["aspiration <causes> bilateral_infiltrates"]},
    {"text": "The patient was discharged on warfarin without INR follow-up. She returned with an INR of 8.4.", "relations": ["missed_inr_followup <causes> supratherapeutic_inr"]},
    {"text": "Compliance with beta-blocker therapy dropped to 30%. The patient presented with atrial fibrillation and rapid ventricular response.", "relations": ["poor_beta_blocker_compliance <causes> atrial_fibrillation_with_rvr"]},
    {"text": "The patient was kept on high-dose diuretics for three weeks. Hypokalemia developed, potassium 2.8 mEq/L.", "relations": ["excessive_diuretic_use <causes> hypokalemia"]},
    {"text": "Prophylactic antibiotics were withheld due to allergy concerns. Surgical site infection occurred on post-op day 3.", "relations": ["withheld_prophylaxis <causes> surgical_site_infection"]},
    {"text": "The isolation room's door was left open during barrier precautions. MRSA transmission occurred to three adjacent patients.", "relations": ["broken_isolation <causes> mrsa_transmission"]},
    {"text": "Central line dressing was not changed for 12 days. Blood culture grew Staph aureus.", "relations": ["overdue_line_dressing <causes> line_infection"]},
    {"text": "Fluids were restricted to 500 mL/day due to heart failure. The patient became acutely confused and disoriented.", "relations": ["severe_fluid_restriction <causes> acute_delirium"]},
    {"text": "The patient's enteral tube was clogged for 36 hours. Albumin fell from 3.1 to 2.4 g/dL in one week.", "relations": ["tube_obstruction <causes> malnutrition"]},
    {"text": "Hemodialysis was delayed by four hours due to technician absence. The patient's potassium peaked at 7.2 mEq/L.", "relations": ["dialysis_delay <causes> hyperkalemia"]},
    {"text": "The ED waiting room temperature dropped to 48 degrees. Three elderly patients developed hypothermia.", "relations": ["cold_environment <causes> hypothermia"]},
    {"text": "Oxygen saturation alarm on the ventilator was silenced. The patient's SpO2 dropped to 74% unnoticed.", "relations": ["disabled_alarm <causes> hypoxemia"]},
    {"text": "Medication reconciliation was skipped at admission. The patient received duplicate doses of metoprolol.", "relations": ["missed_reconciliation <causes> drug_overdose"]},
    {"text": "The phlebotomist drew a potassium sample without a tourniquet. The lab reported K+ of 6.8 mEq/L.", "relations": ["improper_blood_draw <causes> spurious_hyperkalemia"]},
    {"text": "The patient received lisinopril without checking renal function. Creatinine increased from 1.8 to 4.1 mg/dL.", "relations": ["acei_without_renal_check <causes> acute_kidney_injury"]},
    {"text": "Stress ulcer prophylaxis was omitted in the ICU. The patient bled 250 mL from a gastric ulcer.", "relations": ["omitted_stress_prophylaxis <causes> stress_ulcer_bleed"]},
    {"text": "The patient's feeding tube was replaced 14 times in two months. He developed severe esophageal stricture.", "relations": ["repeated_tube_replacement <causes> esophageal_stricture"]},
    {"text": "Skin breakdown was documented but pressure relief was not adjusted. Sacral pressure ulcer progressed from stage 1 to stage 3.", "relations": ["inadequate_pressure_relief <causes> pressure_ulcer_progression"]},
    {"text": "The patient was on metronidazole for 21 days straight. Peripheral neuropathy developed in both feet.", "relations": ["prolonged_metronidazole <causes> peripheral_neuropathy"]},
    {"text": "Magnesium supplementation was withheld for 10 days. The patient developed polymorphic ventricular tachycardia.", "relations": ["hypomagnesemia <causes> polymorphic_vt"]},
    {"text": "The nurse failed to elevate the head of the bed. Aspiration pneumonia developed on day 4.", "relations": ["flat_bed_positioning <causes> aspiration_pneumonia"]},
    {"text": "Insulin was not ordered at discharge. The patient's blood glucose was 467 mg/dL by day 2 at home.", "relations": ["omitted_insulin_discharge <causes> diabetic_hyperglycemia"]},
    {"text": "The patient received ibuprofen 800 mg TID for 6 weeks with existing chronic kidney disease. Creatinine rose 0.8 points.", "relations": ["nsaid_overuse_with_ckd <causes> acute_kidney_injury"]},
    {"text": "Anticoagulation reversal was delayed 3 hours after the patient's fall. Subdural hematoma expanded significantly.", "relations": ["delayed_reversal <causes> hematoma_expansion"]},
    {"text": "The patient was kept supine for 48 hours post-operatively. Pulmonary atelectasis developed in the left lower lobe.", "relations": ["prolonged_supine_position <causes> atelectasis"]},
    {"text": "Nutritional assessment was not performed on admission. The patient lost 12 pounds in two weeks.", "relations": ["missed_nutritional_assessment <causes> malnutrition_progression"]},
    {"text": "The femoral catheter dressing was saturated with blood and not changed. Cellulitis spread up the leg.", "relations": ["inadequate_dressing_care <causes> cellulitis"]},
    {"text": "Calcium gluconate was not given during the hyperkalemia crisis. QRS duration widened to 140 ms.", "relations": ["missed_calcium_gluconate <causes> peaked_t_waves"]},
    {"text": "The patient's oxygen delivery system became disconnected at 3 AM. Pulse oximetry readings were not obtained.", "relations": ["disconnected_oxygen <causes> silent_hypoxemia"]},
    {"text": "Nasogastric tube feeding was continued after proper placement was not confirmed. Aspiration occurred.", "relations": ["unconfirmed_tube_placement <causes> aspiration"]},
    {"text": "Heparin was infused without a weight-based protocol adjustment. The patient developed heparin-induced thrombocytopenia.", "relations": ["excessive_heparin_dosing <causes> hit"]},
    {"text": "Foley catheter was left in place for 23 days without indication. Urinary tract infection with sepsis developed.", "relations": ["prolonged_catheterization <causes> catheter_associated_uti"]},
    {"text": "The patient stopped taking their home beta-blocker abruptly. Hypertensive crisis and angina occurred within 12 hours.", "relations": ["beta_blocker_withdrawal <causes> rebound_hypertension"]},
    {"text": "Physical therapy was not initiated for 5 days post-stroke. Shoulder subluxation developed.", "relations": ["delayed_pt <causes> shoulder_subluxation"]},
    {"text": "The ICU nurse was covering two units. Patient vital signs were checked only once per shift.", "relations": ["excessive_nurse_workload <causes> monitoring_gaps"]},
    {"text": "Gentamicin dosing was not adjusted for age and renal function. Ototoxicity with permanent hearing loss occurred.", "relations": ["improper_aminoglycoside_dosing <causes> ototoxicity"]},
    {"text": "The patient's pain was untreated for 18 hours post-op. Delirium and agitation necessitated sedation.", "relations": ["untreated_postop_pain <causes> delirium"]},
    {"text": "The nephrologist's recommendations for phosphate binders were not implemented. The patient's phosphate rose to 9.2 mg/dL.", "relations": ["missed_nephrology_recs <causes> hyperphosphatemia"]},
    {"text": "The patient missed three physical therapy sessions. The contracture progressed from 30 to 60 degrees.", "relations": ["missed_pt_sessions <causes> contracture_progression"]},
    {"text": "Acetaminophen dosing was not tracked across multiple orders. The patient received 6,000 mg in 24 hours.", "relations": ["untracked_acetaminophen <causes> hepatotoxicity_risk"]},
    {"text": "The IV site was not changed for 11 days. Phlebitis developed with erythema extending 8 cm from the site.", "relations": ["prolonged_iv_dwell <causes> phlebitis"]},
    {"text": "Glucose monitoring was performed only at 7 AM. Nocturnal hypoglycemia went undetected.", "relations": ["infrequent_glucose_checks <causes> nocturnal_hypoglycemia"]},
    {"text": "The patient received three different blood pressure medications without baseline labs. Symptomatic hypotension developed.", "relations": ["unmonitored_antihypertensive_initiation <causes> symptomatic_hypotension"]},
    {"text": "Prophylactic low-molecular-weight heparin was omitted due to cost. Deep vein thrombosis formed in the left leg.", "relations": ["omitted_thromboprophylaxis <causes> dvt"]},
    {"text": "Communication between day and night shift nurses failed. The patient's allergy history was not updated, and the patient received a sulfonamide.", "relations": ["missed_shift_communication <causes> allergic_reaction"]},
    {"text": "The patient remained on NPO status for seven days. Severe hypoalbuminemia developed.", "relations": ["prolonged_npo_status <causes> hypoalbuminemia"]},
    {"text": "Bowel obstruction from fecal impaction was not recognized. The patient became septic.", "relations": ["unrecognized_fecal_impaction <causes> sepsis"]},
    {"text": "The insulin infusion pump malfunctioned silently for four hours. Diabetic ketoacidosis with pH 6.95 developed.", "relations": ["insulin_pump_malfunction <causes> dka"]},
    {"text": "The patient's temperature spiked to 39.8 C but antibiotics were not ordered for 6 hours. Blood cultures grew bacteria.", "relations": ["delayed_antibiotic_initiation <causes> sepsis_progression"]},
    {"text": "Ventilator settings were not adjusted when compliance dropped. Barotrauma with pneumothorax occurred.", "relations": ["maladapted_ventilator_settings <causes> pneumothorax"]},
    {"text": "The patient's albumin level remained at 2.1 g/dL for two weeks without intervention. Ankles developed severe pitting edema.", "relations": ["untreated_hypoalbuminemia <causes> peripheral_edema"]},
]

FINANCE_IMPLICIT = [
    {"text": "Regional banks reported rising NPL ratios of 8.2%. Deposit outflows accelerated at a rate of 2% per week.", "relations": ["rising_npl_ratios <causes> deposit_outflows"]},
    {"text": "The Fed raised rates 75 basis points in one month. Mortgage applications fell 28% in the following quarter.", "relations": ["rate_increase <causes> mortgage_decline"]},
    {"text": "Collateral values in the repo market dropped below margin thresholds. Forced position closures cascaded across the trading floor.", "relations": ["collateral_decline <causes> forced_position_closure"]},
    {"text": "Three mid-size regional banks failed within one week. Counterparty risk premiums spiked 240 basis points.", "relations": ["bank_failures <causes> counterparty_risk_increase"]},
    {"text": "R&D spending was cut by 40% to preserve margins. The product pipeline stalled with only one new candidate.", "relations": ["rd_cuts <causes> pipeline_stagnation"]},
    {"text": "Inventory turnover slowed to 45 days from 28 days. Working capital dried up, forcing a credit line drawdown.", "relations": ["slow_inventory_turnover <causes> working_capital_shortage"]},
    {"text": "The company's credit rating was downgraded two notches. Bond yields widened by 180 basis points.", "relations": ["credit_downgrade <causes> yield_widening"]},
    {"text": "Revenue guidance was slashed by 15%. The stock opened down 22% the next morning.", "relations": ["guidance_reduction <causes> stock_price_decline"]},
    {"text": "The sole supplier of microchips announced a 6-month production halt. Automotive manufacturers idled assembly lines.", "relations": ["supplier_production_halt <causes> assembly_line_idling"]},
    {"text": "Unemployment rose 0.8% in one quarter. Consumer spending fell, driving retail same-store sales down 12%.", "relations": ["unemployment_increase <causes> retail_sales_decline"]},
    {"text": "Interest rates on commercial real estate loans jumped 150 basis points. Cap rates compressed and deal volume fell 60%.", "relations": ["cre_rate_increase <causes> deal_volume_decline"]},
    {"text": "Oil prices fell below $30 per barrel. Upstream capital expenditures were slashed by $200 billion.", "relations": ["oil_price_collapse <causes> capex_cuts"]},
    {"text": "The company's customer concentration risk reached 35% from one account. A single customer contract cancellation would destroy profitability.", "relations": ["high_customer_concentration <causes> business_fragility"]},
    {"text": "Gross margins compressed by 340 basis points due to input cost inflation. Operating leverage turned negative.", "relations": ["margin_compression <causes> negative_operating_leverage"]},
    {"text": "The company's debt maturity wall loomed with $2.1B due in one year. Refinancing risk soared as credit spreads widened.", "relations": ["debt_maturity_wall <causes> refinancing_risk_increase"]},
    {"text": "Private equity fund raising fell 55% year-over-year. Dry powder available for acquisitions shrank dramatically.", "relations": ["reduced_fundraising <causes> dry_powder_decline"]},
    {"text": "Commercial paper markets froze as counterparty confidence evaporated. Short-term funding costs spiked to 8%.", "relations": ["cp_market_freeze <causes> funding_cost_increase"]},
    {"text": "The company missed earnings for the third straight quarter. Institutional investors began redemption requests.", "relations": ["earnings_misses <causes> investor_redemptions"]},
    {"text": "Supply chain disruptions persisted for eight months. Customer lead times extended, eroding competitive advantage.", "relations": ["supply_chain_disruption <causes> lead_time_extension"]},
    {"text": "The company's enterprise value fell below book value. Activist investors began accumulating shares.", "relations": ["below_book_valuation <causes> activist_accumulation"]},
    {"text": "Currency depreciation of 18% made exports cheaper but imports more expensive. Net margin fell from 12% to 8%.", "relations": ["currency_depreciation <causes> margin_compression"]},
    {"text": "Default rates on subprime auto loans reached 6.2%. Asset-backed security spreads widened by 200 basis points.", "relations": ["high_subprime_defaults <causes> abs_spread_widening"]},
    {"text": "The company implemented aggressive price increases of 15%. Customer churn accelerated, volume fell 22%.", "relations": ["aggressive_price_increases <causes> customer_churn"]},
    {"text": "Venture capital funding for the sector evaporated. Startup burn rates outpaced available runway by six months.", "relations": ["vc_funding_freeze <causes> startup_cash_crisis"]},
    {"text": "Fixed costs remained at 65% of revenue as sales declined. Breakeven point shifted higher.", "relations": ["high_fixed_cost_ratio <causes> higher_breakeven"]},
    {"text": "The company's working capital cycle deteriorated to 90 days. Cash conversion fell to near zero.", "relations": ["deteriorating_wcc <causes> cash_conversion_decline"]},
    {"text": "Dividend coverage fell to 0.8x earnings. The board suspended dividend payments the following quarter.", "relations": ["low_dividend_coverage <causes> dividend_suspension"]},
    {"text": "Foreign exchange hedges expired without renewal due to cost constraints. Unhedged exposure to the euro surged 45%.", "relations": ["expired_fx_hedges <causes> currency_exposure_increase"]},
    {"text": "The company's beta rose from 1.2 to 1.8 due to earnings volatility. Cost of equity increased 340 basis points.", "relations": ["higher_beta <causes> cost_of_equity_increase"]},
    {"text": "Customer acquisition costs doubled to $850 per user. Unit economics turned negative.", "relations": ["rising_cac <causes> negative_unit_economics"]},
    {"text": "The company failed to meet environmental compliance standards. Regulatory fines of $45M were assessed.", "relations": ["environmental_non_compliance <causes> regulatory_fines"]},
    {"text": "Employee attrition jumped to 28% annually. Institutional knowledge walked out the door.", "relations": ["high_attrition <causes> knowledge_loss"]},
    {"text": "The company's patent portfolio was invalidated by a court ruling. Generic competitors entered the market immediately.", "relations": ["patent_invalidation <causes> generic_competition"]},
    {"text": "Marketing spend was cut by 50% to preserve cash. Brand awareness metrics fell 35% in three months.", "relations": ["marketing_cuts <causes> brand_awareness_decline"]},
    {"text": "Accounts payable stretched to 90 days due to liquidity pressure. Supplier relationships deteriorated.", "relations": ["extended_ap_terms <causes> supplier_relationship_strain"]},
    {"text": "The company's Altman Z-score fell to 1.3, deep in distress territory. Credit rating agencies issued negative outlooks.", "relations": ["low_z_score <causes> credit_negative_outlook"]},
    {"text": "Customer payment terms stretched from Net 30 to Net 60. Days sales outstanding jumped 40%.", "relations": ["extended_customer_terms <causes> dso_increase"]},
    {"text": "The company's data center experienced a catastrophic failure. Service unavailability lasted 18 hours.", "relations": ["data_center_failure <causes> service_outage"]},
    {"text": "Competitor X launched a disruptive product at half the price. Market share fell from 23% to 16% in six months.", "relations": ["competitive_disruption <causes> market_share_loss"]},
    {"text": "The company's junk bond rating was maintained while peers upgraded. Borrowing costs widened 120 basis points.", "relations": ["rating_lag <causes> borrowing_cost_widening"]},
    {"text": "Geographic revenue concentration in one region hit 52%. Political instability in that region threatened 40% of revenue.", "relations": ["geographic_concentration <causes> revenue_risk"]},
    {"text": "The company's customer retention rate fell from 88% to 71%. Lifetime value decreased 35%.", "relations": ["declining_retention <causes> ltv_decline"]},
    {"text": "Raw material costs spiked 45% with no commodity hedges in place. Gross margin fell 450 basis points.", "relations": ["commodity_spike_unhedged <causes> margin_compression"]},
    {"text": "The company delayed the IPO due to market turmoil. Private investors demanded 40% more equity for the same funding round.", "relations": ["delayed_ipo <causes> equity_dilution"]},
    {"text": "Accounts receivable aging exceeded 120 days for 15% of balances. Bad debt reserves were increased by $18M.", "relations": ["aged_receivables <causes> bad_debt_increase"]},
    {"text": "The company's debt covenant permitted a maximum leverage ratio of 3.5x. Leverage reached 3.8x after acquisitions.", "relations": ["covenant_breach <causes> default_risk_increase"]},
    {"text": "Post-acquisition integration was bungled, losing 30% of target customers. Synergies materialized at only 15% of plan.", "relations": ["failed_integration <causes> synergy_shortfall"]},
    {"text": "The company entered 12 new geographic markets simultaneously. Operating expenses exceeded plan by $120M.", "relations": ["aggressive_expansion <causes> cost_overrun"]},
]

MANUFACTURING_IMPLICIT = [
    {"text": "The sole-source supplier missed three consecutive delivery windows. The assembly line ran out of critical components.", "relations": ["supplier_delivery_failure <causes> assembly_line_stoppage"]},
    {"text": "Humidity in the warehouse exceeded 80% for six days. PCB corrosion was found in 12% of units.", "relations": ["high_humidity <causes> pcb_corrosion"]},
    {"text": "Preventive maintenance was deferred for two quarters due to budget cuts. Unplanned downtime increased 40%.", "relations": ["deferred_maintenance <causes> unplanned_downtime"]},
    {"text": "Coolant levels were not checked for 15 hours. The spindle motor seized, requiring a full replacement.", "relations": ["unchecked_coolant <causes> spindle_motor_seizure"]},
    {"text": "The incoming inspection step was removed to reduce cycle time. Defective raw material entered production and contaminated 200 units.", "relations": ["skipped_incoming_inspection <causes> defective_material_in_production"]},
    {"text": "Tolerance stack-up analysis was not performed on the new fixture. Final assembly rejection rate hit 15%.", "relations": ["missing_tolerance_analysis <causes> high_assembly_rejection_rate"]},
    {"text": "The facility's air conditioning system failed and was not repaired for 48 hours. Component soldering became intermittent.", "relations": ["ac_system_failure <causes> solder_intermittent"]},
    {"text": "Machine calibration was skipped to meet deadline pressure. 340 units produced were out of specification.", "relations": ["skipped_calibration <causes> out_of_spec_production"]},
    {"text": "The warehouse temperature spiked to 42 degrees Celsius during heat wave. Plastic raw material warped in storage.", "relations": ["extreme_warehouse_temperature <causes> raw_material_warping"]},
    {"text": "Lubrication oil was not changed on the CNC machine for 6 months. Bearing friction increased, causing vibration.", "relations": ["overdue_lubrication <causes> bearing_vibration"]},
    {"text": "Quality training for shift B was deferred indefinitely. Defect rate on that shift doubled.", "relations": ["deferred_training <causes> defect_rate_increase"]},
    {"text": "The supplier of rare earth magnets reduced purity from 99.8% to 99.2%. Component magnetization fell below specification.", "relations": ["reduced_material_purity <causes> magnetization_shortfall"]},
    {"text": "Tool wear was not monitored on the punch press. Excessive wear caused dimensional drift.", "relations": ["unmonitored_tool_wear <causes> dimensional_drift"]},
    {"text": "The 3D printer's resin tank was contaminated with metal particles. Ten batches of prototypes failed structural testing.", "relations": ["contaminated_resin <causes> prototype_failures"]},
    {"text": "Electrostatic discharge (ESD) protocols were relaxed during high-volume production. Component failure rates jumped to 0.8%.", "relations": ["relaxed_esd_protocols <causes> component_failure_increase"]},
    {"text": "The factory's emergency backup power system was not tested for nine months. When the main grid failed, all equipment shut down.", "relations": ["untested_backup_power <causes> production_shutdown"]},
    {"text": "Die casting mold temperature control drifted to 180 degrees Celsius from the setpoint of 200. Parts shrank by 0.3%.", "relations": ["mold_temperature_drift <causes> part_shrinkage"]},
    {"text": "The supplier of fasteners switched to a lower-grade coating. Rust developed on assembled subassemblies within two weeks.", "relations": ["fastener_coating_downgrade <causes> rust_formation"]},
    {"text": "A key machine was moved to accommodate new equipment. Misalignment caused runout exceeding 0.05 mm on all parts.", "relations": ["machine_realignment <causes> runout_increase"]},
    {"text": "Humidity control was disabled in the electronics assembly clean room to save energy. Static-sensitive component failures surged.", "relations": ["disabled_humidity_control <causes> static_damage"]},
    {"text": "The production scheduler did not account for setup time between product changeovers. Makespan exceeded plan by 8 hours daily.", "relations": ["inadequate_setup_time_allocation <causes> schedule_overrun"]},
    {"text": "Raw material specification sheets were not updated after vendor changes. Incompatible material was used in batch 412.", "relations": ["outdated_material_specs <causes> incompatible_material_use"]},
    {"text": "The conveyor belt speed was increased 15% to boost throughput. Part damage and misalignment multiplied.", "relations": ["increased_conveyor_speed <causes> part_damage"]},
    {"text": "Contamination in the paint booth was not cleaned for 30 days. Orange peel texture and dirt specs appeared in 8% of painted units.", "relations": ["paint_booth_contamination <causes> paint_defects"]},
    {"text": "The torque wrench calibration was overdue by four months. Fasteners were under-torqued, leading to joint failures.", "relations": ["uncalibrated_torque_wrench <causes> fastener_under_torque"]},
    {"text": "Compressed air pressure dropped from 6 bar to 4 bar due to a leak in the main line. Pneumatic tools operated sluggishly.", "relations": ["compressed_air_pressure_drop <causes> tool_performance_decline"]},
    {"text": "The laser cutter's lens was not cleaned for two weeks. Cutting power fell 12%, increasing edge roughness.", "relations": ["dirty_laser_lens <causes> edge_roughness_increase"]},
    {"text": "Safety interlocks on the welding station were disabled for faster operation. A technician was burned when they entered the live zone.", "relations": ["disabled_safety_interlocks <causes> workplace_injury"]},
    {"text": "Statistical process control charts were not reviewed for six weeks. The process drifted out of control undetected.", "relations": ["missed_spc_review <causes> process_drift"]},
    {"text": "The supplier's factory experienced a fire that destroyed 40% of production capacity. Delivery times jumped from 4 weeks to 12 weeks.", "relations": ["supplier_factory_fire <causes> delivery_delay"]},
    {"text": "First-piece inspection was skipped on the new mold due to schedule pressure. An entire first run of 5,000 units was defective.", "relations": ["skipped_first_piece_inspection <causes> defective_first_run"]},
    {"text": "Batch numbering system was changed without updating the material management system. Obsolete material was used instead of current stock.", "relations": ["batch_numbering_mismatch <causes> obsolete_material_use"]},
    {"text": "The robotic arm's servo motor showed early signs of wear. Positional accuracy degraded from +/- 0.1 mm to +/- 0.3 mm.", "relations": ["servo_motor_wear <causes> positional_accuracy_degradation"]},
    {"text": "Incoming rubber was stored above a heat source during the summer. Material became brittle and failed flex testing.", "relations": ["improper_material_storage <causes> material_brittleness"]},
    {"text": "The quality engineer's shift was eliminated to reduce overhead. Quality escapes increased 35% without that oversight.", "relations": ["eliminated_quality_role <causes> quality_escape_increase"]},
    {"text": "Metal chips from a neighboring machine contaminated the assembly station. Three units suffered short circuits.", "relations": ["metal_chip_contamination <causes> electrical_shorts"]},
    {"text": "A critical bearing supplier ceased operations with no transition period. The production line halted for six days.", "relations": ["supplier_closure <causes> production_halt"]},
    {"text": "Humidity in the adhesive storage room fell to 25% from the required 50%. Epoxy lost viscosity, creating weak bonds.", "relations": ["low_humidity_adhesive_storage <causes> weak_bonds"]},
    {"text": "The vibration isolation table failed due to deferred maintenance. Precision machining tolerances drifted ±0.08 mm.", "relations": ["isolation_table_failure <causes> machining_tolerance_drift"]},
    {"text": "Shift handoff documentation was eliminated as a cost-saving measure. Important process parameters were missed, drifting into out-of-control zones.", "relations": ["eliminated_shift_handoff <causes> missed_parameters"]},
]
